// <auto-generated />
namespace Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test2904 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test2904));
        
        string IMigrationMetadata.Id
        {
            get { return "201704291238166_test2904"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
